[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = { workspace = true }

#[target.'cfg(not(target_arch = "spirv"))'.dependencies]
#shader = { path = "../shader" }

[build-dependencies]
spirv-builder = { workspace = true }
